2020-12-22 17:42:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-22 17:42:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-22 17:42:03 WARNING (MainThread) [homeassistant.components.tuya] The 'tuya' option is deprecated, please remove it from your configuration
2020-12-22 17:42:08 ERROR (MainThread) [homeassistant.components.sensor] The speedtestdotnet platform for the sensor integration does not support platform setup. Please remove it from your config.
2020-12-22 17:42:08 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_open of <Listener(Thread-7, initial daemon)>>: on_open() missing 1 required positional argument: 'ws'
2020-12-22 17:42:08 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:42:08 ERROR (MainThread) [homeassistant.components.binary_sensor] The smartweather platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
2020-12-22 17:42:10 ERROR (MainThread) [hole] Can not load data from *hole: 123
2020-12-22 17:42:10 ERROR (MainThread) [homeassistant.components.pi_hole.config_flow] Failed to import: Can not load data from *hole: 123
2020-12-22 17:42:10 WARNING (Amcrest Backyard) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:13 WARNING (Amcrest Backyard) [homeassistant.components.amcrest] Error while processing events from Backyard camera: CommError(ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1549100>: Failed to establish a new connection: [Errno 113] Host is unreachable'))")))
2020-12-22 17:42:17 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:18 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform amcrest is taking over 10 seconds.
2020-12-22 17:42:18 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform amcrest is taking over 10 seconds.
2020-12-22 17:42:18 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform amcrest is taking over 10 seconds.
2020-12-22 17:42:20 ERROR (SyncWorker_0) [homeassistant.components.amcrest.camera] Could not get Backyard camera attributes due to error: CommError
2020-12-22 17:42:23 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:26 ERROR (SyncWorker_5) [homeassistant.components.amcrest.binary_sensor] Could not update Backyard Motion Detected binary sensor due to error: CommError
2020-12-22 17:42:29 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:32 ERROR (SyncWorker_3) [homeassistant.components.amcrest.sensor] Could not update Backyard SD Used sensor due to error: CommError
2020-12-22 17:42:35 WARNING (Amcrest Backyard) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:42:38 WARNING (Amcrest Backyard) [homeassistant.components.amcrest] Error while processing events from Backyard camera: CommError(ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xad1fb490>: Failed to establish a new connection: [Errno 113] Host is unreachable'))")))
2020-12-22 17:42:42 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:45 ERROR (SyncWorker_0) [homeassistant.components.amcrest] Backyard camera offline: Too many errors
2020-12-22 17:42:45 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.backyard is taking over 10 seconds
2020-12-22 17:42:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:50 WARNING (MainThread) [homeassistant.components.camera] Updating amcrest camera took longer than the scheduled update interval 0:00:15
2020-12-22 17:42:51 ERROR (SyncWorker_5) [homeassistant.components.amcrest.camera] Could not get Backyard camera attributes due to error: CommError
2020-12-22 17:42:52 WARNING (MainThread) [homeassistant.components.sensor] Updating amcrest sensor took longer than the scheduled update interval 0:00:10
2020-12-22 17:42:52 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.backyard_sd_used is taking over 10 seconds
2020-12-22 17:42:54 WARNING (Amcrest Backyard) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:42:57 WARNING (Amcrest Backyard) [homeassistant.components.amcrest] Error while processing events from Backyard camera: CommError(ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb15befd0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))")))
2020-12-22 17:43:00 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:43:02 WARNING (MainThread) [homeassistant.components.sensor] Updating amcrest sensor took longer than the scheduled update interval 0:00:10
2020-12-22 17:43:03 ERROR (SyncWorker_2) [homeassistant.components.amcrest.sensor] Could not update Backyard SD Used sensor due to error: CommError
2020-12-22 17:43:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:43:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:43:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:44:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:44:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:44:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:45:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:45:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:45:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:46:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:46:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:46:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:47:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:47:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:47:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:48:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:48:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:48:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:49:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:49:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:49:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:50:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:50:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:50:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:51:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:51:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:51:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:52:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:52:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:52:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:53:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:53:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:53:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:54:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:54:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:54:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:55:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:55:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:55:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:56:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:56:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:56:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:57:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:57:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:57:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:58:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:58:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:58:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 17:59:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:59:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 17:59:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:00:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:00:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:00:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:01:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:01:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:01:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:02:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:02:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:02:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:03:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:03:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:03:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:04:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:04:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:04:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:05:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:05:09 WARNING (Thread-9) [pychromecast.socket_client] [Hamm House(192.168.1.137):8009] Heartbeat timeout, resetting connection
2020-12-22 18:05:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:05:39 ERROR (Thread-9) [pychromecast.socket_client] [Hamm House(192.168.1.137):8009] Failed to connect to service Chromecast-98346b092f06c6476556bc2831a197ed._googlecast._tcp.local., retrying in 5.0s
2020-12-22 18:05:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:06:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:06:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:06:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:07:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:07:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:07:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:08:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:08:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:08:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:09:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:09:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:09:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:10:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:10:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:10:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:11:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:11:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:11:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:12:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:12:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:12:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:13:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:13:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:13:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:14:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:14:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:14:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:15:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:15:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:15:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:16:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:16:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:16:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:17:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:17:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:17:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:18:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:18:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:18:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:19:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:19:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:19:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:20:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:20:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:20:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:21:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:21:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:21:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:22:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:22:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:22:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:23:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:23:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:23:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:24:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:24:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:24:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:25:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:25:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:25:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:26:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:26:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:26:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:27:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:27:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:27:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:28:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:28:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:28:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:29:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:29:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:29:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:30:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:30:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:30:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:31:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:31:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:31:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:32:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:32:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:32:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:33:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:33:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:33:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:34:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:34:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:34:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:35:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:35:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:35:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:36:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:36:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:36:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:37:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:37:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:37:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:38:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:38:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:38:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:39:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:39:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:39:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:40:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:40:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:40:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:41:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:41:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:41:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:42:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:42:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:42:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:43:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:43:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:43:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:44:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:44:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:44:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:45:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:45:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:45:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:46:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:46:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:46:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:47:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:47:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:47:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:48:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:48:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:48:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:49:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:49:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:49:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:50:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:50:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:50:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:51:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:51:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:51:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:52:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:52:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:52:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:53:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:53:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:53:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:54:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:54:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:54:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:55:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:55:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:55:48 WARNING (SyncWorker_2) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:56:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:56:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:56:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:57:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:57:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:57:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:58:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:58:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:58:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 18:59:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:59:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 18:59:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:00:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:00:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:00:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:01:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:01:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:01:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:02:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:02:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:02:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:03:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:03:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:03:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:04:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:04:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:04:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:05:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:05:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:05:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:06:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:06:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:06:48 WARNING (SyncWorker_0) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:07:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:07:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:07:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:08:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:08:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:08:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:09:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:09:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:09:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:10:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:10:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:10:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:11:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:11:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:11:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:12:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:12:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:12:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:13:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:13:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:13:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:14:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:14:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:14:48 WARNING (SyncWorker_5) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:15:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:15:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:15:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:16:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:16:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:16:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:17:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:17:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:17:48 WARNING (SyncWorker_1) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:18:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:18:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:18:48 WARNING (SyncWorker_3) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:19:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:19:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:19:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:20:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:20:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:20:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:21:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:21:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:21:48 WARNING (SyncWorker_6) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
2020-12-22 19:22:07 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:22:37 ERROR (Thread-6) [websocket] error from callback <bound method Listener.on_message of <Listener(Thread-7, initial daemon)>>: on_message() missing 1 required positional argument: 'message'
2020-12-22 19:22:48 WARNING (SyncWorker_4) [amcrest.http] <None:None> Trying again due to error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.128', port=80): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at ADDRESS>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))
